---
title: "Plotting Allele Frequencies - SNPs within dokb gene"
output:
  pdf_document: default
  html_document: default
date: '2024-04-23'
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


```{r, include = FALSE}
library(data.table)
library(stringr)
library(ggplot2)
```

```{r}
pos_table <- fread(file = "/Users/arteen/Desktop/pop_gen_out/revisions/lowVhigh/alleleF_plotting.txt")
pos_table <- pos_table[,c(1,2,4,5)]
colnames(pos_table) <- c("CHROM", "POS", "REF", "ALT")
pos_table <- as.data.frame(pos_table)
pos_table$match <- paste0(pos_table$CHROM, "_", pos_table$POS)

syncFile <- fread(file = "/Users/arteen/Desktop/pop_gen_out/actual_sync/unmerged_subsetted.sync")
syncFile <- as.data.frame(syncFile)
colnames(syncFile) <- c("CHROM", "POS", "REF",
                        "Ancestor1","Ancestor2","Ancestor3","Ancestor4",
                        "Control1","Control2","Control3","Control4",
                        "Down1","Down2","Down3","Down4", 
                        "Up1","Up2","Up3","Up4")

syncFile$match <- paste0(syncFile$CHROM, "_", syncFile$POS)
#syncFile <- as.data.frame(syncFile) # wants to stay a data.table for some reason

# 3L 13440910	13442420 is dokb
syncFile <- subset(syncFile, syncFile$CHROM == "3L")
syncFile <- subset(syncFile, syncFile$POS > 13440910)
syncFile <- subset(syncFile, syncFile$POS < 13442420)
row.names(syncFile) <- 1:nrow(syncFile) # just in case rownames act up


# Throwing the potential SNP right up top (will also appear in the rest of the plotting)
syncFile <- rbind(syncFile[26,], syncFile)

# I am assuming biallelic counts here and this will most likely break if triallelic
for (i in 1:nrow(syncFile)) {
  #i <- 1
  allele <- syncFile$match[i]
  
  syncRow <- syncFile[i,]
  # Average and SE of ancestor
  ancestralDF <- data.frame(matrix(nrow = 4, ncol = 5))
  colnames(ancestralDF) <- c("A", "T", "C", "G", "AF")
  row.names(ancestralDF) <- colnames(syncRow)[4:7]
  
  for (j in 4:7) { # for ancestral
    a <- as.integer(str_split_i(syncRow[, j], ":", i = 1))
    t <- as.integer(str_split_i(syncRow[, j], ":", i = 2))
    c <- as.integer(str_split_i(syncRow[, j], ":", i = 3))
    g <- as.integer(str_split_i(syncRow[, j], ":", i = 4))
    
    ancestralDF[c(j - 3), 1] <- a
    ancestralDF[c(j - 3), 2] <- t
    ancestralDF[c(j - 3), 3] <- c
    ancestralDF[c(j - 3), 4] <- g
    
    if (syncRow$REF == "A"){
      ancestralDF[c(j - 3), 5] <- (t + c + g) / (a + t + c + g)
    } else if(syncRow$REF == "T"){
      ancestralDF[c(j - 3), 5] <- (a + c + g) / (a + t + c + g)
    } else if(syncRow$REF == "C"){
      ancestralDF[c(j - 3), 5] <- (a + t + g) / (a + t + c + g)
    } else if(syncRow$REF == "G"){
      ancestralDF[c(j - 3), 5] <- (a + t + c) / (a + t + c + g)
    } else { 
      cat("There is no reference") 
      next
    }
  }
  
  ancestorMean <- mean(ancestralDF$AF)
  ancestorSE <- sd(ancestralDF$AF) / sqrt(nrow(ancestralDF))
  
  # Control
  controlDF <- data.frame(matrix(nrow = 4, ncol = 5))
  colnames(controlDF) <- c("A", "T", "C", "G", "AF")
  row.names(controlDF) <- colnames(syncRow)[8:11]
  
  for (j in 8:11) { # for ancestral
    a <- as.integer(str_split_i(syncRow[, j], ":", i = 1))
    t <- as.integer(str_split_i(syncRow[, j], ":", i = 2))
    c <- as.integer(str_split_i(syncRow[, j], ":", i = 3))
    g <- as.integer(str_split_i(syncRow[, j], ":", i = 4))
    
    controlDF[c(j - 7), 1] <- a
    controlDF[c(j - 7), 2] <- t
    controlDF[c(j - 7), 3] <- c
    controlDF[c(j - 7), 4] <- g
    
    if (syncRow$REF == "A"){
      controlDF[c(j - 7), 5] <- (t + c + g) / (a + t + c + g)
    } else if(syncRow$REF == "T"){
      controlDF[c(j - 7), 5] <- (a + c + g) / (a + t + c + g)
    } else if(syncRow$REF == "C"){
      controlDF[c(j - 7), 5] <- (a + t + g) / (a + t + c + g)
    } else if(syncRow$REF == "G"){
      controlDF[c(j - 7), 5] <- (a + t + c) / (a + t + c + g)
    } else { 
      cat("There is no reference") 
      next
    }
  }
  
  controlMean <- mean(controlDF$AF)
  controlSE <- sd(controlDF$AF) / sqrt(nrow(controlDF))
  
  ## Down
  downDF <- data.frame(matrix(nrow = 4, ncol = 5))
  colnames(downDF) <- c("A", "T", "C", "G", "AF")
  row.names(downDF) <- colnames(syncRow)[12:15]
  
  for (j in 12:15) { # for ancestral
    a <- as.integer(str_split_i(syncRow[, j], ":", i = 1))
    t <- as.integer(str_split_i(syncRow[, j], ":", i = 2))
    c <- as.integer(str_split_i(syncRow[, j], ":", i = 3))
    g <- as.integer(str_split_i(syncRow[, j], ":", i = 4))
    
    downDF[c(j - 11), 1] <- a
    downDF[c(j - 11), 2] <- t
    downDF[c(j - 11), 3] <- c
    downDF[c(j - 11), 4] <- g
    
    if (syncRow$REF == "A"){
      downDF[c(j - 11), 5] <- (t + c + g) / (a + t + c + g)
    } else if(syncRow$REF == "T"){
      downDF[c(j - 11), 5] <- (a + c + g) / (a + t + c + g)
    } else if(syncRow$REF == "C"){
      downDF[c(j - 11), 5] <- (a + t + g) / (a + t + c + g)
    } else if(syncRow$REF == "G"){
      downDF[c(j - 11), 5] <- (a + t + c) / (a + t + c + g)
    } else { 
      cat("There is no reference") 
      next
    }
  }
  
  downMean <- mean(downDF$AF)
  downSE <- sd(downDF$AF) / sqrt(nrow(downDF))
  
  
  ## Up
  upDF <- data.frame(matrix(nrow = 4, ncol = 5))
  colnames(upDF) <- c("A", "T", "C", "G", "AF")
  row.names(upDF) <- colnames(syncRow)[16:19]
  
  for (j in 16:19) { # for ancestral
    a <- as.integer(str_split_i(syncRow[, j], ":", i = 1))
    t <- as.integer(str_split_i(syncRow[, j], ":", i = 2))
    c <- as.integer(str_split_i(syncRow[, j], ":", i = 3))
    g <- as.integer(str_split_i(syncRow[, j], ":", i = 4))
    
    upDF[c(j - 15), 1] <- a
    upDF[c(j - 15), 2] <- t
    upDF[c(j - 15), 3] <- c
    upDF[c(j - 15), 4] <- g
    
    if (syncRow$REF == "A"){
      upDF[c(j - 15), 5] <- (t + c + g) / (a + t + c + g)
    } else if(syncRow$REF == "T"){
      upDF[c(j - 15), 5] <- (a + c + g) / (a + t + c + g)
    } else if(syncRow$REF == "C"){
      upDF[c(j - 15), 5] <- (a + t + g) / (a + t + c + g)
    } else if(syncRow$REF == "G"){
      upDF[c(j - 15), 5] <- (a + t + c) / (a + t + c + g)
    } else { 
      cat("There is no reference") 
      next
    }
  }
  
  upMean <- mean(upDF$AF)
  upSE <- sd(upDF$AF) / sqrt(nrow(upDF))
  
  
  alleleF <- c(ancestorMean,
               controlMean,
               downMean,
               upMean)
               # controlDF[1, 5], controlDF[2, 5], controlDF[3, 5], controlDF[4, 5],
               # downDF[1, 5], downDF[2, 5], downDF[3, 5], downDF[4, 5],
               # upDF[1, 5], upDF[2, 5], upDF[3, 5], upDF[4, 5])
  
  treatment <- c("Ancestor",
                 "Control",
                 "Low",
                 "High")
                 # rep("Control", 4),
                 # rep("Low", 4),
                 # rep("High", 4))
  
  SE_list <- c(ancestorSE,
               controlSE,
               downSE,
               upSE)
               #rep(NA, 12))
  
  alleleF_df <- data.frame(alleleFreq = alleleF,
                           SE = SE_list,
                           treatment = treatment)
  
  alleleF_df$treatment <- factor(alleleF_df$treatment, levels = c("Ancestor", "Control", "Low", "High"))
  
  ancestral_df <- alleleF_df[1,]
  alleleF_df <- alleleF_df[-1,]
  
  pd <-  position_dodge(width = 0.3)
  
  alleleFreqPlot <- ggplot() +
    geom_point(data = ancestral_df,
                aes(x = treatment, y = alleleFreq, color = treatment),
                 size = 2.5) +
    
    geom_errorbar(data = ancestral_df, 
                  aes(x = treatment, y = alleleFreq, ymin = alleleFreq - SE, ymax = alleleFreq + SE, color = treatment),
                  width = 0.15, size = 0.7, alpha = 1) +
    
    geom_point(data = alleleF_df,
                aes(x = treatment, y = alleleFreq, color = treatment),
                 size = 2.5, alpha = 0.7) +
    
    geom_errorbar(data = alleleF_df, 
                  aes(x = treatment, y = alleleFreq, ymin = alleleFreq - SE, ymax = alleleFreq + SE, color = treatment),
                  width = 0.15, size = 0.7, alpha = 1) +
    
    
    theme_classic() +
    theme( plot.title = element_text(), axis.text = element_text(face = "bold")) +
    xlab("Treatment") +
    ylab("Allele Frequency") +
    ggtitle(syncRow$match)
  suppressWarnings(print(alleleFreqPlot))
}

```

